name: navigation
version: 0.0.1
publish_to: none
description: Project navigation module

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.6.0
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

dev_dependencies:
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true